### ISSUE TITLE
[Bug] Misplaced volume symbol and wrong name

### ISSUE THREAD

**Issue by libalis** [lxqt/lxqt-themes#57] opened 2022-02-16 22:50 UTC
![KDE-Plasma](https://user-images.githubusercontent.com/45124869/154370095-1eebf9c0-e89f-41f0-979f-030f27bb2ecd.png)
![KDE-Plasma (1)](https://user-images.githubusercontent.com/45124869/154370219-5dab2156-f585-4622-9b16-1ba517c72769.png)

As you can see on the screenshots, KDE Plasma is the only theme where the volume icon is shifted downwards. I also thought KDE Plasma had the letters k, d, e and p in capital letters, but this is apparently not the case here.

##### System Information
* Distribution & Version: openSUSE Tumbleweed
* Kernel: 5.16.8
* Qt Version: 5.15
* lxqt-build-tools Version: 1.0.0
* libqtxdg Version: 1.0.0
* Package version: 1.0.0

**Comment by stefonarch** [comment] 2022-02-17 07:49
The problem is more that some other icons don't reserve the transparent 3px on top for the blue upper line which appears usually on  hovering.
And brightness is  not styled at all in the theme and with a dark palette it looks out of place. We agreed that usually nobody will use a dark palette in this theme, but at least the button should be in line.

Maybe we should remove the hover effect.


https://user-images.githubusercontent.com/10681413/154429312-6d3cd97e-05ab-4926-8c7d-89edb5825f1d.mp4

**Comment by stefonarch** [comment] 2022-02-17 11:39
If you like to test: copy the kde-plasma theme folder from `/usr/share/lxqt/themes/` to `~/.local/share/lxqt/themes/` and change the volume plugin in lxqt-panel.qss like that:
```
/*
 * Volume plugin
 */
#VolumePlugin QToolButton {
    margin: 3px;
    border-top: 3px solid transparent;
    color: rgba(54, 54, 54, 60%);
}


VolumePopup {
    border: 1px solid rgba(155, 155, 155, 100%);
    background:rgba(240, 240, 240, 100%);
    padding: 4px;
}
```
You'll find the modified theme on top on the themes list in lxqt-appearance.

**Comment by libalis** [comment] 2022-02-17 23:12
I understand, thank you, maybe for consistency reasons this margin should be deleted completely.
But what about the second point: the name (Kde-plasma instead of KDE Plasma)?

**Comment by stefonarch** [comment] 2022-04-06 17:50
Prepared a PR for both things, but others should be merged before probably.

**Comment by libalis** [comment] 2022-04-06 18:02
Great news. Thank you so much.

**Comment by ianfarrell47** [comment] 2022-04-07 21:50
I personally would like to retain the blue overlines and add them to widgets where they are missing. This is what KDE Plasma does, and as it stands they appear in LXQt on Application Menu, Task Switcher, Volume Control, Show Desktop, and perhaps more. I looked at the .qss file and it appears they are intended to appear in Mount Plugin and others, but for some reason do not appear.

**Comment by ianfarrell47** [comment] 2022-04-07 22:58
>looked at the .qss file and it appears they are intended to appear in Mount Plugin and others
Changing `#LXQtMountPlugin MountButton` to `#LXQtMountPlugin` restores the overline.

**Comment by stefonarch** [comment] 2022-04-08 05:26
I've no problem with that, will look into it, this should apply also on backlight plugin I guess. 
On my vertical panel  I saw that for the keyboard indicator it doesn't suit well, the underlines.

**Closed** 2022-04-15 07:10 UTC
